[package]

name = "websocket"
version = "0.0.1"
authors = ["Konstantin Stepanov <me@kstep.me>"]

[lib]
name = "websocket"

[dependencies]
url = "*"
openssl = "*"
rust-crypto = "*"
rustc-serialize = "*"
