[package]

name = "websocket"
version = "0.0.1"
authors = ["Konstantin Stepanov <me@kstep.me>"]

[lib]
name = "websocket"

[dependencies]
url = "*"
openssl = "*"
rustc-serialize = "*"

[dependencies.sha1]
git = "https://github.com/kstep/rust-sha1.git"
